# Generated by Django 5.0.6 on 2024-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Container",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("container_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("formula", models.CharField(max_length=100)),
                ("mass", models.FloatField()),
                ("volume", models.FloatField()),
                ("density", models.FloatField()),
                ("location", models.CharField(max_length=100)),
                ("precursor", models.BooleanField()),
                ("cas", models.CharField(max_length=100)),
                ("qualification", models.IntegerField()),
            ],
        ),
    ]
