# Generated by Django 5.0.6 on 2024-09-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reagents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_id",
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
