# Generated by Django 5.0.6 on 2024-06-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_role_invitecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invite_codes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
