# Generated by Django 5.0.6 on 2024-07-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="middle name"),
        ),
    ]
